name: KernelSU For nabu

on:
  workflow_dispatch:

jobs:
  KSUForSirius:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
          sudo apt clean

      - name: Clone Sources and Toolchain
        run: |
          git clone https://github.com/liqideqq/android_kernel_xiaomi_nabu --depth=1 -b 13.0 --recurse-submodules nabu_Kernel
          git clone https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b --depth=1 --single-branch --no-tags -b lineage-20.0 ~/clang
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android-10.0.0_r47 --depth=1 --single-branch --no-tags ~/aarch64-linux-android-4.9
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 -b android-10.0.0_r47 --depth=1 --single-branch --no-tags ~/arm-linux-androideabi-4.9
          git clone https://github.com/SakuraNotStupid/AnyKernel3

      - name: Compile Kernel (MIUI)
        run: |
          CLANG=~/clang/bin
          GCC32=~/arm-linux-androideabi-4.9/bin
          GCC64=~/aarch64-linux-android-4.9/bin
          export PATH=$CLANG:$GCC64:$GCC32:$PATH
          output_dir=out
          export args="-j$(nproc --all) ARCH=arm64 SUBARCH=arm64 O=$output_dir CC=clang CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi- CLANG_TRIPLE=aarch64-linux-gnu- LLVM=1"
          pushd nabu_Kernel
          make ${args} nabu_defconfig
          make ${args}
          popd

      - name: Package the Kernel (MIUI)
        run: |
          cp -v nabu_Kernel/out/arch/arm64/boot/Image.gz AnyKernel3/
          pushd AnyKernel3
          7z a -mx9 ../nabu_KernelSU.zip *
          popd

      - name: Create Config Info
        run: |
          echo "Device: Xiaomi tablet 5
          Code: nabu
          Build Code: ${{ github.run_number }}
          KernelSU For nabu" >> INFO.txt

      - name: Upload Kernel Package to GH-Release
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: nabu_KernelSU.zip
          name: "nabu_KernelSU"
          tag: "${{ github.run_number }}_nabu_KernelSU"
          bodyFile: "INFO.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
